sudo: required

services:
  - docker

before_install:
  - docker build -t kapsse/docker-react:latest -f dev.Dockerfile .

script:
  - docker run kapsse/docker-react:latest npm run tests -- --coverage
